### ISSUE TITLE
Can you do it for only one language, not dual?

### ISSUE THREAD

**Issue by Scr561** [muzuiget/dualsub-supports#10]
I've been using the extension for a while.
I ask you.

Can you do it for only one language, not dual?

Double tongue confusing.
*Can you please add a single language option for me?

I'd appreciate it if you answered.

**Comment by muzuiget** [comment]
It doesn't make sense, If you only need one language, why you use this extension?

**Comment by Scr561** [comment]
> It doesn't make sense, If you only need one language, why you use this extension?

What extension do I need to use?

My goal is to choose a Turkish subtitle with a single click.
Can you tell me if you know of another extension that does this?

**Comment by Scr561** [comment]
> Yani, altyazı dilini seçmek için yalnızca özel kullanıcı arayüzüne mi ihtiyacınız var?

Yes youtube's own options are very boring.
With only one click you can select Turkish auto.
Whether or not subtitle support.

Can this be done?
I can't find it all overturned.
Please help me.

I couldn't find any scripts associated with Tampermonkey.
If I could, can I just do it with the script?

**Comment by muzuiget** [comment]
It it not big deal on technology, but need to redesign to extension UI.

**Comment by Scr561** [comment]
> Bu teknoloji üzerinde büyük bir anlaşma değil, ancak kullanıcı arabirimini genişletmek için yeniden tasarlanması gerekiyor.

You can't do something about it?
Can you make automatic googe translation with one click even if there is no subtitle support?

Except only the languages that the video supports.
How long does it take to extend the interface.

If he wants you to do this, will you?

**Comment by Scr561** [comment]
It doesn't have to be online.
It can also work offline.

**Comment by muzuiget** [comment]
v0.4.2 now support "Single" subtitle mode, this make Dualsub toolbar take over player's subtitle selection.
