### ISSUE TITLE
【BUG】Not Working on Google Chrome Version 72 + Firefox 65

### ISSUE THREAD

**Issue by SJTUboy** [muzuiget/dualsub-supports#12]
Browser Version: Google Chrome Version 72.0.3626.119
++
Firefox 65.0.1 (64-bit)

**Comment by SJTUboy** [comment]
Add description: setting buttton is still there, but the subtitle doesn't show up.

Any one the same problem?

**Comment by muzuiget** [comment]
I try in Version Chrome Version 72.0.3626.119, it work fine.

Can you post the problem video url?

**Comment by SJTUboy** [comment]
Tried again just now, it worked fine.

Sorry to bother you guys. 

I will close the issue. Thanks again for the amazing tool!
