### ISSUE TITLE
下载字幕后，不能加载

### ISSUE THREAD

**Issue by lszyqww** [muzuiget/dualsub-supports#14]
有本地视频文件， 不能加载下下来的双语字幕。

**Comment by lszyqww** [comment]
> 有本地视频文件， 不能加载下下来的双语字幕。

例如视频 https://www.youtube.com/watch?v=z-IR48Mb3W0

**Comment by muzuiget** [comment]
你是怎么下载字幕文件的？

**Comment by lszyqww** [comment]
双语字幕。中文（中国）和英文，都是用户上传的非机器翻译。

**Comment by muzuiget** [comment]
能把文件发上来吗？

**Comment by lszyqww** [comment]
https://calm-1256106613.cos.ap-chengdu.myqcloud.com/What%20is%20depression%20-%20Helen%20M.%20Farrell.ass?q-sign-algorithm=sha1&q-ak=AKID78RNTG5eLmstqK4YG6qc3flwY0bOt2c7&q-sign-time=1555936301;1555938101&q-key-time=1555936301;1555938101&q-header-list=&q-url-param-list=&q-signature=04daec6556c129a33bb13804941638e283d7c1f9&x-cos-security-token=28a6468800d73b9cd0d0cf56e042989d9531f51d10001

**Comment by muzuiget** [comment]
下载失败。

**Comment by lszyqww** [comment]
[https://calm-1256106613.cos.ap-chengdu.myqcloud.com/What%20is%20depression%20-%20Helen%20M.%20Farrell.ass]
试试这个

**Comment by lszyqww** [comment]
[https://calm-1256106613.cos.ap-chengdu.myqcloud.com/What%20is%20depression%20-%20Helen%20M.%20Farrell.ass](url)试试这个

**Comment by lszyqww** [comment]
另外，今天我在网页版上使用dualsub的时候，发现视频全屏后两个字幕的字体差距太大了，好像第一次使用的时候没出现过这种情况..

**Comment by muzuiget** [comment]
这个文件我试过是可以的，应该是你的播放器问题。

字体问题是因为 YouTube 又改版了，用 `font-size: smaller` 现在不能适应视频画面变动后的情况，只能用绝对值，例如 `font-size: 32px` 。

**Comment by lszyqww** [comment]
不行，我晚上又试了下，用VLC和Potplayer都不能播放。QQ影音说字幕加载成功，播放视频的时候也并没有成功显示字幕。我换渠道下载Youtube视频文件，也还是不能成功显示字幕。

**Comment by muzuiget** [comment]
我装了 VLC 试了，VLC 确实不行。MPlayer 倒是可以。

**Comment by muzuiget** [comment]
修复了，刷新浏览器再下载测试一下。

**Comment by lszyqww** [comment]
的确可以了。但是还是建议优化下那个字幕全屏后大小差异太大的问题..
另外，双语字幕有些时候导致原来的中文/英文字幕已经存在两行了，但被压缩为了一行，所以下下来的字幕或者观看的时候就会发现一些单词间隔了2个空格，我觉得这也是有点瑕疵的...虽然可以看双语已经很不错了。
