### ISSUE TITLE
Dualsub doesn't work any longer

### ISSUE THREAD

**Issue by sinus223** [muzuiget/dualsub-supports#15]
I have been very satisfied with Dualsub, but today I asserted that it doesn't work any longer. The regular captions button of youtube works, but whenever I adjust the language option of the App DUALSUB, no subtitles are shown at all. Is the problem related to an update of Chrome/Windows/Youtube?

**Comment by muzuiget** [comment]
I have tested, still work fine.

Press <kbd>F12</kbd> to open DevTools, switch to Network tab, then type `appsopt.com` in filter bar, then choose your subtitle on Dualsub toolbar, then check the any error show on Network tab.

**Comment by btiancai1** [comment]
Dualsub is still working well, but download the subtitle doesn't work any longer. Could you please check the subtitle download website? Thx

**Comment by sinus223** [comment]
After deleting all existing cookies in Chrome it works again.

**Comment by pigxbun** [comment]
Same issue🥹
