### ISSUE TITLE
Auto pause after each subtitle 

### ISSUE THREAD

**Issue by nokrizz** [muzuiget/dualsub-supports#16]
This extension is great for learning languages but it has a downside. It's almost impossible to read the original subtitle and the translation before it's gone, not to mention, it's even less possible to analyze the language that you're learning. Hitting the pause button manually is just exhausting.

I have a suggestion that would make this extension even better. It would be great if you could add an auto pause function so that the player could pause at the end of each subtitle for a set period of time. I would suggest to make it adjustable from 0 to 10 seconds, also to have an option to set it to infinite time.

The second suggestion, I would love to see as well an auto repeat function to repeat each subtitle I'd say from 1 to 5 times.

**Comment by muzuiget** [comment]
For language learning purpose, I think the best way is download the video and the subtitle file, then play with desktop video player. There should be a lot of this kind of players.

You can download the merged subtitle from  https://dualsub-app.appspot.com/, or get the url from Dualsub option panel.

So I am not attend to add this feature.
