### ISSUE TITLE
能不能依照第一字幕自動選擇第二字幕（這是功能請求而非bug）

### ISSUE THREAD

**Issue by XiaoPanPanKevinPan** [muzuiget/dualsub-supports#17]
（只是個小小的願望，沒有很重要）
我注意到我的youtube在影片同時有多語言字幕時，字幕優先顯示順位為[中文台灣zh-TW -> 中文中國zh-CN -> 英文en]。
我希望
　　當　第一字幕顯示中文字幕　時，　第二字幕顯示英文字幕　；
　　當　第一字幕顯示英文字幕　時，　第二字幕自動將英文字幕翻譯成中文字幕　。
比如可以在優先選擇語言中，做這種事：
　　`en?zh-TW||zh-CN, en:zh-hant?en` // `?`表示"if第一字幕為......"，`||`表示"或者" 
或者
　　`(zh-TW||zh-CN)en, (en)en:zh-hant` // `(...)`表示"if第一字幕為..."，`||`表示"或者")
這類型的
(以上只是我小小的願望，為我可能的打擾先說聲抱歉)

**Comment by muzuiget** [comment]
我觉得让你直接填一个 JS 函数算了，传给该函数当前的环境数据，函数返回语言代码。

不过这种冷门需求我不太想改 UI 了，直接把代码写到 `localStoage` 里就好。

**Comment by muzuiget** [comment]
这需求太冷门，我不打算做了。
