### ISSUE TITLE
Transliteration/PinYin Option

### ISSUE THREAD

**Issue by Some83** [muzuiget/dualsub-supports#19]
Could You do option for Transliteration/Romanisation of subtitles?

I mean, It can be Second line.
It can Be Third Line.
I suppose, depending on advancement level of user, one would wish to be able to view:
Chinese with PinYin and English subtitles.
And other would like to have only Romanised Hindi without English translation.
Romanisation it would be good for:
Chinese - PinYin
Japanese, 
Hebrew, Arabic {It could be even Right To Left Transliteration}
Hindi, Korean
And even Russian, but I do not really need it, but I suppose 
I would think some people would like IPA phonetization of English.
{I do not recommend them to use such technique as helpful way to learn English, but nevertheless some people would choose}

What is more.
I would like that transliteration would be in options:
As 2nd/3rd Line.
Or Transliteration next to each word, but in very much different color.

I know even there is ruby html tag, which could make it possible to put each transliterated word above original word with easiness.
<ruby > <rt> </rt> <ruby>

I could add there is such plugin:
panlatin.
And there is plugin to see code for plugins.
But it does not Romanise, transliterate subtitles on YouTube.

**Comment by muzuiget** [comment]
Haha, honestly, this is the reason I write this extension.

I want to markup the kanji's pronunciation in Japanese. That is why I convert the subtitle on server side, so I can use the natural language processing tool which isn't written with JavaScript , and the directory is so big and it can't be packed into the extension install file.

Current problem is YouTube's subtitle render implement, it render in plain text, it's diffcult to do align layout, That is why I don't release this feature to public. YouTube doesn't provides any API about how to custom the subtitle, it need more time to do the reverse engineering.

**Comment by Some83** [comment]
I need to mention, that Japanese is most complicated in transliteration.

I suppose: Hindi, Korean are much simpler.
Then Arabic, Hebrew (As it is right to Left, but transliteration could be also right to left, {or tfel-ot-htgir})
They do not require massive dictionary.
(They can if you want compensate for very often omitted vowels, but I do not suppose such compensation is important.)
Then chinese pinYin.
Even English phonetisation to IPA is much less complicated than Japanese transliteration.
At least It can transliterate this two Japanese alphabet with 100 letters each.
Hindi has dual letters but it does not matter in transliteration.

PanLatin extension does not do it Fully for Japanese.
However there is option for loading dictionaries.

**Comment by muzuiget** [comment]
Now v0.4.1 support Chinese Pinyin and Japanese Hiragana annotation.

I close this issue because this feature request description isn't explicit enough.
