### ISSUE TITLE
Original Language option

### ISSUE THREAD

**Issue by Some83** [muzuiget/dualsub-supports#20]
I would like to have better language options.

I would like to have first line of subtitles in the same language as original language of audio of video.
{Which, could be difficult to address as there are mistakes in language tag of video, and even youtube titles of video are different in different languages}.

And then I would like to have in second line, languages in decreasing order of my ability level which for me are:
1 native Polish
2 native like level English
3 german
4 spanish
4 russian
5 other romanic languages
6 other slavic languages
7 other germanic languages

So as You see I also would like to have certain complicated option.
As language groups.
Slavic, Germanic, Romanic, semitic: Arabic/Hebrew.
For example, when I watch video in Dutch, I would like to have subtiles in English or German if avaible.

When I watch language in romanic language, I would like Second subtitles to be also in Romanic if avaible.
When I watch video in Slavic language, I would like to have second subtitles in Polish or Russian or other slavic languages if avaible.
When I watch video in some nordic language (that is germanic subGroup) I would like to have second subtitles in German.
SubGroup in Slavic are: WestSlavic, EastSlavic, South Slavic.

Do not bother about this SubGroups.
Just Ordinary Groups are enough for the beginning.

**Comment by muzuiget** [comment]
Do this feature satisfy?

https://github.com/muzuiget/dualsub-supports/blob/master/docs/setting.md#preferred-language-selection

**Comment by Some83** [comment]
That is cool.
But what is option for original language?
I would like that Dual Sub plugin would turn automatically first line of subtitles in original Language.

**Comment by muzuiget** [comment]
v0.4.2 now support "Single" subtitle mode, this make Dualsub toolbar take over player's subtitle selection.
