### ISSUE TITLE
Css Font Size does not apply in version introducing pinyin

### ISSUE THREAD

**Issue by Some83** [muzuiget/dualsub-supports#21]
Css Font Size and color does not apply in plugin version introducing pinyin.
So I suppose it is bug.
And this pinYin looks really cool, really Great. :-)
But I would also like to have option to give it another color than Chinese, and also for Hiragana.

I will be looking forward for introducing version with Arabic, Hebrew, Hindi/Devanagari ir even Korean Transliteration.

**Comment by Some83** [comment]
Css Font Size and color does not apply in plugin version introducing pinyin.
So I suppose it is bug.
And this pinYin looks really cool, really Great. :-)
But I would also like to have option to give it another color than Chinese, as for Hiragana.

I will be looking forward for introducing version with Arabic, Hebrew, Hindi/Devanagari ir even Korean Transliteration.

**Comment by muzuiget** [comment]
v0.4.0 has breaking changes. you need to update the CSS code.

Document: https://dualsub.netlify.com/setting?id=subtitle-style
