### ISSUE TITLE
完全無法使用Q_Q

### ISSUE THREAD

**Issue by justin1627** [muzuiget/dualsub-supports#22]
如題，youtube內跑不出雙字幕
(重開機過了)

**Comment by muzuiget** [comment]
我刚才试了一下，没问题呀。

**Comment by justin1627** [comment]
![ds1](https://user-images.githubusercontent.com/55445062/65220652-c17fe700-daed-11e9-91e0-7885ca52ef04.png)
使用原版字幕，將DS兩個都關閉的時候，原本的字幕會正常顯示

![ds2](https://user-images.githubusercontent.com/55445062/65220654-c17fe700-daed-11e9-94e0-a0893672204e.png)
打開DS，不僅雙語沒有打開，連原本的字幕都沒有顯示了?

剛剛將chrome更新了，還是一樣。
電腦是new surface pro(感覺就跟他沒有關係?)

**Comment by muzuiget** [comment]
能否给出视频地址？

**Comment by justin1627** [comment]
抱歉晚回，是每個視頻都不能用QQ

**Comment by XiaoPanPanKevinPan** [comment]
+1
在選擇第二字幕之後，Console顯示
`OPTIONS https://dualsub-app.appspot.com/api/timedtext?a=ex&n=2816201691&d=JiL2KrFvF8nQaZg%2BOrFztIS6cI1SAHbAmxe55k63YN25BcJ64j7BqldsGRpd8urhtZG1kGYtvMcjBrcIY01TLvpHKo%2FE3XzlhGfi3b8Sqjao3SYIHmHF04KsOF5uvnRCbf%2BnjNa609phGofF%2B%2FUUv7o1X9c1KjF2rC6fDaIQRG%2Bi4%2F%2FToyr2NJXdm8Qv1EzWXMWvWjg8VcXdvpv%2BQ4g0tcDl4txlbGKdybK%2BB3TrnemyIohofe%2BP%2FvOoiqYiExucbcHB%2BHmkkXWSsC1BpCpFaVs02XUPL8mWY9RtOv%2FfL3PUKhYxh6zBd7FYMTwg48kjSsyLPJ68AkCtkwNKOyhQpL7aKAWUmNPXCxQSucj4qwERz21g2Q215V1uH0pSwUj1oy%2FYxW8z0DO1jfwKKKFLrzzMgVedEPcFOQevzwy0vJA2hAjEJ%2BY0QX15TgLyanBdrl4AeJMGLmf9OUvGdzu5o2zLAm8MkD1xapZ%2BEJA1midGUq34bkHfGxQJ5eUE%2FZgGqkOG2LtzAM0du4PAqnGO4ORhN9eE%2Fqn5gpDmJzfvnjIAL%2FcgCCUoNX7G%2FALYTn1j%2B5ZMlfjZAzEU5klpUdu0LrLoz51zMzbJazBgbou82%2FlwxT%2Fq2A5FwUd1NMJ9TKAyxFAgRZUfXq7%2BIo9qYsUNFO%2F4EzWxbsRPFYxq0sf4fgLdYTVqItOiREpI9Q%3D%3D&s=e9fd012b2b08a14a6e362e332417fbbe 400`
以及
`Access to XMLHttpRequest at 'https://dualsub-app.appspot.com/api/timedtext?a=ex&n=2816201691&d=JiL2KrFvF8nQaZg%2BOrFztIS6cI1SAHbAmxe55k63YN25BcJ64j7BqldsGRpd8urhtZG1kGYtvMcjBrcIY01TLvpHKo%2FE3XzlhGfi3b8Sqjao3SYIHmHF04KsOF5uvnRCbf%2BnjNa609phGofF%2B%2FUUv7o1X9c1KjF2rC6fDaIQRG%2Bi4%2F%2FToyr2NJXdm8Qv1EzWXMWvWjg8VcXdvpv%2BQ4g0tcDl4txlbGKdybK%2BB3TrnemyIohofe%2BP%2FvOoiqYiExucbcHB%2BHmkkXWSsC1BpCpFaVs02XUPL8mWY9RtOv%2FfL3PUKhYxh6zBd7FYMTwg48kjSsyLPJ68AkCtkwNKOyhQpL7aKAWUmNPXCxQSucj4qwERz21g2Q215V1uH0pSwUj1oy%2FYxW8z0DO1jfwKKKFLrzzMgVedEPcFOQevzwy0vJA2hAjEJ%2BY0QX15TgLyanBdrl4AeJMGLmf9OUvGdzu5o2zLAm8MkD1xapZ%2BEJA1midGUq34bkHfGxQJ5eUE%2FZgGqkOG2LtzAM0du4PAqnGO4ORhN9eE%2Fqn5gpDmJzfvnjIAL%2FcgCCUoNX7G%2FALYTn1j%2B5ZMlfjZAzEU5klpUdu0LrLoz51zMzbJazBgbou82%2FlwxT%2Fq2A5FwUd1NMJ9TKAyxFAgRZUfXq7%2BIo9qYsUNFO%2F4EzWxbsRPFYxq0sf4fgLdYTVqItOiREpI9Q%3D%3D&s=e9fd012b2b08a14a6e362e332417fbbe' (redirected from 'https://www.youtube.com/api/timedtext?v=5IbiEyZXOBk&asr_langs=de%2Cen%2Ces%2Cfr%2Cit%2Cja%2Cko%2Cnl%2Cpt%2Cru&caps=asr&hl=zh-TW&ip=0.0.0.0&ipbits=0&expire=1569790209&sparams=ip%2Cipbits%2Cexpire%2Cv%2Casr_langs%2Ccaps&signature=689575A0884E4D108267CC4AD270B9A4F28F17DB.403FC88960A8EA3A41D31469674713E0D0BC67F7&key=yt8&lang=en&fmt=srv3&xorb=2&xobt=3&xovt=3') from origin 'https://www.youtube.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by muzuiget** [comment]
@justin1627 在视频页按 <kbd>F12</kbd> 调处开发者控制台，切换到 `Network` 标签页，搜索框里输入 `appspot.com`，然后再切换一下字幕，看看是否有请求错误，`Console` 是否有错误输出。

**Comment by muzuiget** [comment]
@XiaoPanPanKevinPan 我什么也没改，请问你在用哪个版本的 Chrome？

**Comment by justin1627** [comment]
![image](https://user-images.githubusercontent.com/55445062/66264834-f8b8fc80-e83e-11e9-8bfa-1fe880a85ea9.png)
 這樣嗎?

**Comment by justin1627** [comment]
![image](https://user-images.githubusercontent.com/55445062/66264856-36b62080-e83f-11e9-9160-954c42876695.png)
這樣嗎?

**Comment by muzuiget** [comment]
似乎是合并字幕地址被屏蔽掉了，你有在用其它带网络请求过滤的扩展吗，先关掉试试？

**Comment by justin1627** [comment]
![image](https://user-images.githubusercontent.com/55445062/66269796-92080300-e87f-11e9-9615-358abad241e9.png)
刪到只剩dualsub也是一樣
![image](https://user-images.githubusercontent.com/55445062/66269822-d5627180-e87f-11e9-9195-9f402fb9129d.png)

**Comment by muzuiget** [comment]
请问你用哪个版本的 Chrome？

**Comment by muzuiget** [comment]
或者试试浏览 https://dualsub-exporter.netlify.com 能否下载一个双语的 ass 文件。

**Comment by justin1627** [comment]
版本:
![image](https://user-images.githubusercontent.com/55445062/66271310-17df7a80-e88f-11e9-83a5-b2ee1ad79f69.png)
一直在跑，沒有東西
![image](https://user-images.githubusercontent.com/55445062/66271318-2ded3b00-e88f-11e9-81e2-743cea88ed4f.png)

**Comment by muzuiget** [comment]
你的电脑系统时间正确吗？是否和实际时间相差太大？

**Comment by justin1627** [comment]
沒有 是正常的

**Comment by muzuiget** [comment]
不如你还是先在控制面板里同步下网络时间吧。

**Comment by justin1627** [comment]
可以了XDD，感謝
