### ISSUE TITLE
建议添加复制单词功能

### ISSUE THREAD

**Issue by tomtomdev** [muzuiget/dualsub-supports#27]
可以参考Potplayer 播放器的字幕取词，
或者Language Learning with netflix 这款chrome插件

http://languagelearningwithnetflix.com/instructions.html#lang=xx

**Comment by muzuiget** [comment]
你是想让文字可以选中？

**Comment by tomtomdev** [comment]
> 你是想让文字可以选中？

是的。具体的效果就是，左键单击英文等字母类单词，就选中并复制单词。

**Comment by muzuiget** [comment]
已在 v0.4.4 里实现。
