### ISSUE TITLE
Error Pinyin Furigana Service is unavailable

### ISSUE THREAD

**Issue by Hanson7300** [muzuiget/dualsub-supports#29]
[https://www.youtube.com/watch?v=jlBRA9auUT0](url) 
视频为英语带繁体中文字幕,在第二字幕选择为繁体转简体的时候,提示 error pinyin furigana service is unavailable
另外中文繁体和简体都在下拉框的最底下,如果能调到上面就好了;ted演讲的视频语言种类很多,怎样保留自己想要的/常用的几个,把其他不常用的语言选项隐藏?

**Comment by muzuiget** [comment]
注音功能我在服务器关掉了，如果是仅仅简繁转换，选“机器翻译”下面的。

**Comment by Hanson7300** [comment]
是我选错选项了/捂脸,不好意思

**Comment by Hanson7300** [comment]
再次试了一下,机器翻译下面的繁体转其他语言正常,繁体转简体,输出还是繁体

**Comment by oudajosefu** [comment]
It doesn't work for me either

**Comment by muzuiget** [comment]
我试了一下，YouTube 本来就如此，把繁体中文翻译到简体中文就是无效的。

**Comment by oudajosefu** [comment]
Can someone please fix this issue. I'm still getting it every time.

**Comment by muzuiget** [comment]
@oudajosefu the machine of the phonetic function take me too much bill, so I shut it down temporarily.

**Comment by muzuiget** [comment]
注音功能重新上线。

Ruby annotations back online.

**Comment by oudajosefu** [comment]
@muzuiget Thank you so much!
