### ISSUE TITLE
Couldn't select specific language for second subtitle and style customization

### ISSUE THREAD

**Issue by MagisDing** [muzuiget/dualsub-supports#3]
Couldn't choose Chinese simplified in the second subtitle menu, or is there any other way to define the position/sequence of the dual subtitles, like display the second one on the top.  Besides, how to adjust the default fonts, please?
[Screenshot](https://cl.ly/c7147e30998d) uploaded here.

PS: this extension conflicts with the extension "magic action".

Best Regards

**Comment by muzuiget** [comment]
Can you give me the issue video url?

I am no idea on the conflict, maybe that extension has changed YouTube layout too much.

**Comment by MagisDing** [comment]
Sorry for the missing message, here is the[link](https://www.youtube.com/watch?v=k8bpv2iqOMQ).

**Comment by muzuiget** [comment]
The video actually doesn't provide "Simplified Chinese" subtitle.
