### ISSUE TITLE
卸载之后字幕无法便会自动生成的语言

### ISSUE THREAD

**Issue by MonsterG** [muzuiget/dualsub-supports#30]
卸载扩展程序或者停用扩展程序后没法还原单英文字母

**Comment by muzuiget** [comment]
这是不可能的，没有改动任何浏览器设置。你可以这样查一下：按 <kbd>F12</kbd> 弹出开发者控制台，切换到 Network 标签页，过滤栏输入 `timedtext` ，然后在 YouTube 播放器切换下字幕，浏览器访问的字幕地址应该是 YouTube 域名下的地址。
