### ISSUE TITLE
Firefox（火狐浏览器）不能正常加载双字幕，通常需要刷新页面才能使用。

### ISSUE THREAD

**Issue by McGiRG3z** [muzuiget/dualsub-supports#31]
![image](https://user-images.githubusercontent.com/48904579/68085532-d259a180-fe7c-11e9-9cd9-843f291464eb.png)
显示：Require page reload to get subtitle data

Chrome中不存在这样的问题，请问可以特意为Firefox修复一下吗？

**Comment by muzuiget** [comment]
确实只有 Firefox 才出现。

**Comment by muzuiget** [comment]
在 `v0.4.5` 修复了。
