### ISSUE TITLE
出现两个字幕选择框，无法使用翻译字幕

### ISSUE THREAD

**Issue by archerlll** [muzuiget/dualsub-supports#36]
![微信截图_20191226153102](https://user-images.githubusercontent.com/42974247/71464537-bdeab300-27f4-11ea-9bdf-b2c4d0b08b6a.png)

**Comment by archerlll** [comment]
应该是从0.6.0版本开始就这样了，之前还会导致不显示字幕，目前是0.6.2

**Comment by muzuiget** [comment]
在设置面板里，“语言” -> “机器翻译语言“ 你填了什么？

**Comment by muzuiget** [comment]
确实是 bug，在 v0.6.3 修复了。
