### ISSUE TITLE
想购买付费的，请问这个是需要每次打开YouTube都是需要点一下设置吗

### ISSUE THREAD

**Issue by yangchen158158** [muzuiget/dualsub-supports#402]
想购买付费的，请问这个是需要每次打开YouTube都是需要手动点一下设置吗，还是可以后台设置好，下次打开视频的哈，字幕就可以自动翻译呢？

**Comment by muzuiget** [comment]
这是两回事。

在扩展设置页面填了有效 API Key，服务器就不会返回 `需要 API Key` 这个错误信息，而是返回翻译结果。

Dualsub 没有语音识别功能，一定要网站或者自己提供原文字幕才能翻译。默认情况下，打开新视频就是沿用上一个视频的字幕是设置，如果原文字幕的语言变了，就需要手动选择一下。

**Comment by muzuiget** [comment]
如果你搞不清楚，先在 YouTube 里使用“简单模式”理解下，这是直接用 YouTube 自己的译文。

**Comment by chuchipang** [comment]
我估計樓主是想付費後雙字幕自動開啓？

自動選擇功能可用於（付費的）標準模式和（不用付費的）簡單模式哦。

設置指南見 [https://www.dualsub.xyz/zh/docs/settings-guide](url) 。
