### ISSUE TITLE
对于youtube 嵌入式不是很友好

### ISSUE THREAD

**Issue by Andy-Yuen** [muzuiget/dualsub-supports#6]
像可汗学院 这种嵌入式的youtube视频就没办法使用
www.khanacademy.org

**Comment by muzuiget** [comment]
做不了的，太多限制了

* 需要申请访问任意域名页面权限
* 页面里有多个 YouTube 播放器
* 动态创建的 YouTube 播放器

只能跳到 YouTube 里看。
