### ISSUE TITLE
Youtube长视频字幕翻译失败

### ISSUE THREAD

**Issue by Felrix** [muzuiget/dualsub-supports#617]
视频链接：https://www.youtube.com/watch?v=V_xro1bcAuA
显示消息：{游客用户：不允许当前时间位置}
![image](https://github.com/user-attachments/assets/eac8f143-41e7-414a-81b2-f2dfbbec83a6)

**Comment by muzuiget** [comment]
需要 API key https://www.dualsub.xyz/zh/docs/pricing.html
