### ISSUE TITLE
无法下载字幕文件

### ISSUE THREAD

**Issue by isummerice** [muzuiget/dualsub-supports#8]
Download .ass file 打开新窗口 
地址为：https://dualsub-app.appspot.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dvz99_kI5mWg

但是无法下载。

非常感谢你的这个插件，对于我这种英语差的人很有帮助，但是我想视频下载后载入字幕一起看。

**Comment by muzuiget** [comment]
我试一下，还是可以的，具体是怎么无法下载呢？点击「开始」后，跳到语言选择页了吗？

**Comment by isummerice** [comment]
那可能是我电脑上安装插件的问题吧。

我的现象是打开一个空白网页，没有跳转成功，没有到选择语言页。

等下我换台电脑看看。

**Comment by muzuiget** [comment]
要对 `dualsub-app.appspot.com` 加入代理，整个 `*.appspot.com` 都在墙外。

**Comment by isummerice** [comment]
我已经开了全局代理，而且其他的 appspot.com 的网站都能打开，
唯独 dualsub-app.appspot.com 无法打开，页面一片空白。

![youtube](https://user-images.githubusercontent.com/29417823/47358846-9afad580-d6fd-11e8-8c22-3d326614e1b2.png)

![dualsub](https://user-images.githubusercontent.com/29417823/47358786-60913880-d6fd-11e8-8317-85f058f299b1.png)

![speechlogger](https://user-images.githubusercontent.com/29417823/47358819-7dc60700-d6fd-11e8-9432-c087dfc3437c.png)

**Comment by muzuiget** [comment]
你按 <F12> 弹出开发者控制台看看有什么错误，切换到 Network 面板，看看哪几个文件没下载到。

**Comment by isummerice** [comment]
![network](https://user-images.githubusercontent.com/29417823/47361622-ff6d6300-d704-11e8-87f7-83f584897a1c.png)

**Comment by muzuiget** [comment]
没注意浏览器默认语言问题，修复了，再试下。

**Comment by isummerice** [comment]
可以下载啦，多谢！
还有，能不能在加个选项：
【下载的文件名使用视频的名称】，而不是用视频地址作为名称。
这样就不用改视频名称了。

**Comment by muzuiget** [comment]
这个可以有，迟点再加上。
